/**
 * База знаний вендоров РФ: реквизиты продуктов, проверенные по вендорским
 * документам и публичным реестрам (`sourceUrl`, дата сверки — `verifiedAt`).
 *
 * Сертификаты ФСТЭК/ФСБ имеют срок действия — при выпуске документов
 * реквизиты выводятся с формулировкой «по состоянию на дату сверки»;
 * периодическая ре-верификация входит в регламент сопровождения базы.
 */

import { VendorHardwareProduct, VendorSoftwareProduct } from './types';

export const VENDOR_SOFTWARE: VendorSoftwareProduct[] = [
  {
    id: 'usergate-ngfw',
    kind: 'software',
    category: 'ngfw',
    name: 'UserGate NGFW (ПО межсетевого экранирования и обнаружения вторжений)',
    vendor: 'ООО «Юзергейт»',
    reestrMinTsifry: '№ 1194',
    certification:
      'Сертификат ФСТЭК России № 3905 (4 уровень доверия; МЭ типов «А», «Б» 4 класса, СОВ сетевого уровня 4 класса)',
    licenseType: 'Бессрочная серверная сублицензия + подписка Security Updates 12 мес.',
    match: /usergate|ngfw|юзергейт/i,
    quantity: {
      answerKey: 'ngfw_clusters_count',
      multiplier: 2,
      unit: 'шт.',
      fallback: '2 шт. (HA-кластер)',
    },
    sourceUrl: 'https://www.usergate.com/ru/products/usergate-ngfw',
    verifiedAt: '2026-08-26',
  },
  {
    id: 'kaspersky-kes',
    kind: 'software',
    category: 'endpoint',
    name: 'Kaspersky Endpoint Security для бизнеса (Расширенный)',
    vendor: 'АО «Лаборатория Касперского»',
    reestrMinTsifry: '№ 207',
    certification: 'Сертификат ФСТЭК России № 4068, сертификат ФСБ России № СФ/019-3471',
    licenseType: 'Срочная сублицензия на 12/36 месяцев',
    match: /kaspersky|касперск|kes\b/i,
    quantity: { answerKey: 'endpoints_count', unit: 'лиц.', fallback: '100 лиц.' },
    sourceUrl: 'https://support.kaspersky.ru/common/certificates/14693',
    verifiedAt: '2026-08-26',
  },
  {
    id: 'cyberpeak-spektr',
    kind: 'software',
    category: 'audit',
    name: 'Cyberpeak «Спектр» (система аудита доступа к неструктурированным данным, DCAP)',
    vendor: 'ООО «Сайберпик»',
    reestrMinTsifry: '№ 12590',
    certification: 'Единый реестр российского ПО (188-ФЗ)',
    licenseType: 'Корпоративная сублицензия на защищаемые файловые хранилища',
    match: /cyberpeak|сайберпик|спектр|аудит.*данн/i,
    quantity: { answerKey: 'storage_audits_count', unit: 'серв.', fallback: '2 серв.' },
    sourceUrl: 'https://cyberpeak.ru',
    verifiedAt: '2026-08-26',
  },
  {
    id: 'vipnet',
    kind: 'software',
    category: 'crypto',
    name: 'ПК ViPNet Coordinator HW 4 / ViPNet Client 4 (СКЗИ, ГОСТ-VPN)',
    vendor: 'АО «ИнфоТеКС»',
    certification:
      'Сертификаты ФСБ России № СФ/124-4900 (Coordinator HW 4, КС3) и № СФ/124-5189 (Client 4, КС1/КС2/КС3)',
    licenseType: 'Бессрочная сублицензия со знаком соответствия ФСБ России',
    match: /vipnet|випнет|гост-?vpn/i,
    quantity: { answerKey: 'vpn_tunnels_count', unit: 'шт.', fallback: '2 шт.' },
    sourceUrl: 'https://infotecs.ru/products/vipnet-coordinator-hw/',
    verifiedAt: '2026-08-26',
  },
  {
    id: 'astra-linux-se',
    kind: 'software',
    category: 'os',
    name: 'Операционная система специального назначения «Astra Linux Special Edition»',
    vendor: 'ООО «РусБИТех-Астра»',
    reestrMinTsifry: '№ 369',
    certification:
      'Сертификат ФСТЭК России № 2557 (1 уровень доверия, максимальный уровень защищённости «Смоленск»)',
    licenseType: 'Серверная лицензия с пакетом обновлений «Стандартный» / «Расширенный»',
    match: /astra|астра/i,
    quantity: { answerKey: 'servers_count', unit: 'серв.', fallback: '4 серв.' },
    sourceUrl:
      'https://wiki.astralinux.ru/kb/sertifikatsiya-fstek-dlya-astra-linux-special-edition-1-6-1-7-187794271.html',
    verifiedAt: '2026-08-26',
  },
  {
    id: 'postgres-pro-enterprise',
    kind: 'software',
    category: 'dbms',
    name: 'СУБД «Postgres Pro Enterprise»',
    vendor: 'ООО «Постгрес Профессиональный»',
    reestrMinTsifry: '№ 104',
    certification:
      'Сертификат ФСТЭК России № 4063 (редакция Enterprise Certified, 4 уровень доверия)',
    licenseType: 'Бессрочная лицензия на серверное ядро (per-Core / per-Socket)',
    match: /postgres|постгрес/i,
    quantity: { answerKey: 'db_clusters_count', multiplier: 2, unit: 'узла', fallback: '2 узла' },
    sourceUrl: 'https://postgrespro.ru/products/postgrespro/enterprisecertified',
    verifiedAt: '2026-08-26',
  },
  {
    id: 'secret-net-studio',
    kind: 'software',
    category: 'nsd',
    name: 'СЗИ от НСД Secret Net Studio',
    vendor: 'ООО «Код Безопасности»',
    reestrMinTsifry: '№ 3855',
    certification: 'Сертификат ФСТЭК России № 3745',
    licenseType: 'Клиентские и серверные лицензии с контролем целостности',
    match: /secret ?net|нсд/i,
    quantity: { answerKey: 'workstations_count', unit: 'лиц.', fallback: 'По числу хостов' },
    sourceUrl: 'https://www.securitycode.ru/products/secret-net-studio/',
    verifiedAt: '2026-08-26',
  },
  {
    id: 'dallas-lock',
    kind: 'software',
    category: 'nsd',
    name: 'СЗИ от НСД Dallas Lock 8.0-C',
    vendor: 'ООО «Конфидент»',
    certification: 'Сертификат соответствия ФСТЭК России (СЗИ от НСД, СКН)',
    licenseType: 'Клиентские и серверные лицензии',
    match: /dallas ?lock|даллас/i,
    quantity: { answerKey: 'workstations_count', unit: 'лиц.', fallback: 'По числу хостов' },
    sourceUrl: 'https://dallaslock.ru',
  },
  {
    id: 'sobol-apmdz',
    kind: 'software',
    category: 'nsd',
    name: 'ПАК «Соболь» (аппаратно-программный модуль доверенной загрузки)',
    vendor: 'ООО «Код Безопасности»',
    certification: 'Сертификат соответствия ФСТЭК России (СДЗ уровня платы расширения)',
    licenseType: 'Аппаратный модуль с лицензией на ПО управления',
    match: /соболь|апмдз|доверенн[ао]й? загрузк/i,
    quantity: { answerKey: 'workstations_count', unit: 'шт.', fallback: 'По числу защищаемых АРМ' },
    sourceUrl: 'https://www.securitycode.ru/products/pak-sobol/',
  },
  {
    id: 'kiber-backup',
    kind: 'software',
    category: 'backup',
    name: 'Система резервного копирования «Кибер Бэкап» (расширенная редакция)',
    vendor: 'ООО «Киберпротект»',
    reestrMinTsifry: '№ 4161',
    certification: 'Сертификат ФСТЭК России № 4753 (версия 18.0, 4 уровень доверия)',
    licenseType: 'Лицензии на физический сервер / виртуальную машину / универсальные',
    match: /кибер ?бэкап|cyber ?backup|резервн\w* копирован/i,
    quantity: { answerKey: 'servers_count', unit: 'лиц.', fallback: '1 компл.' },
    sourceUrl: 'https://cyberprotect.ru/products/backup/fstek',
    verifiedAt: '2026-08-26',
  },
  {
    id: 'maxpatrol-siem',
    kind: 'software',
    category: 'siem',
    name: 'Система мониторинга событий ИБ MaxPatrol SIEM',
    vendor: 'АО «Позитив Текнолоджиз»',
    reestrMinTsifry: '№ 1143',
    certification: 'Сертификат ФСТЭК России № 4980 (4 уровень доверия)',
    licenseType: 'Лицензия по количеству активов/EPS + техническая поддержка',
    match: /maxpatrol|макспатрол/i,
    quantity: { answerKey: 'event_sources_count', unit: 'источников', fallback: '1 компл.' },
    sourceUrl: 'https://www.ptsecurity.com/ru-ru/products/mpsiem/',
    verifiedAt: '2026-08-26',
  },
  {
    id: 'kaspersky-kuma',
    kind: 'software',
    category: 'siem',
    name: 'SIEM-платформа Kaspersky Unified Monitoring and Analysis Platform (KUMA)',
    vendor: 'АО «Лаборатория Касперского»',
    reestrMinTsifry: '№ 9128',
    certification: 'Единый реестр российского ПО (188-ФЗ)',
    licenseType: 'Срочная лицензия по потоку событий (EPS)',
    match: /(?<![a-z])kuma(?![a-z])|(?<![а-яё])кума(?![а-яё])|unified monitoring/i,
    quantity: { answerKey: 'event_sources_count', unit: 'источников', fallback: '1 компл.' },
    sourceUrl: 'https://reestr.digital.gov.ru/reestr/310478/',
    verifiedAt: '2026-08-26',
  },
  {
    id: 'zvirt',
    kind: 'software',
    category: 'virtualization',
    name: 'Платформа серверной виртуализации zVirt',
    vendor: 'ООО «Орион софт»',
    reestrMinTsifry: '№ 4984',
    certification: 'Единый реестр российского ПО (188-ФЗ)',
    licenseType: 'Лицензия на физический сервер (по числу CPU) + подписка на обновления',
    match: /zvirt|звирт/i,
    quantity: { answerKey: 'hypervisor_hosts_count', unit: 'хостов', fallback: '2 хоста' },
    sourceUrl: 'https://www.orionsoft.ru/zvirt',
    verifiedAt: '2026-08-26',
  },
  {
    id: 'ald-pro',
    kind: 'software',
    category: 'directory',
    name: 'Служба каталога ALD Pro (домен предприятия, замена Microsoft Active Directory)',
    vendor: 'ООО «РусБИТех-Астра»',
    certification: 'Единый реестр российского ПО (188-ФЗ)',
    licenseType: 'Лицензия на управляемое рабочее место / сервер',
    match: /ald ?pro|служб[аы] каталог|active ?directory/i,
    quantity: {
      answerKey: 'workstations_count',
      unit: 'АРМ',
      fallback: 'По числу управляемых АРМ',
    },
    sourceUrl: 'https://aldpro.ru',
  },
  {
    id: 'red-os',
    kind: 'software',
    category: 'os',
    name: 'Операционная система «РЕД ОС»',
    vendor: 'ООО «РЕД СОФТ»',
    certification: 'Сертификат соответствия ФСТЭК России (профиль защиты ОС типа «А»)',
    licenseType: 'Лицензия на сервер / рабочую станцию с техподдержкой',
    match: /(?<![а-яё])ред\s?ос(?![а-яё])|(?<![a-z])red\s?os(?![a-z])/i,
    quantity: { answerKey: 'servers_count', unit: 'серв.', fallback: '2 серв.' },
    sourceUrl: 'https://redos.red-soft.ru',
  },
  {
    id: 'termidesk',
    kind: 'software',
    category: 'virtualization',
    name: 'Платформа виртуализации рабочих мест (VDI) Termidesk',
    vendor: 'ООО «УВЕОН — облачные технологии» (ГК «Астра»)',
    certification: 'Единый реестр российского ПО (188-ФЗ)',
    licenseType: 'Конкурентные лицензии по числу одновременных подключений',
    match: /termidesk|термидеск|vdi/i,
    quantity: {
      answerKey: 'vdi_users_count',
      unit: 'подключений',
      fallback: 'По числу пользователей VDI',
    },
    sourceUrl: 'https://termidesk.ru',
  },
  {
    id: 'cryptopro-csp',
    kind: 'software',
    category: 'crypto',
    name: 'СКЗИ «КриптоПро CSP»',
    vendor: 'ООО «КРИПТО-ПРО»',
    certification: 'Сертификаты ФСБ России (классы КС1/КС2/КС3)',
    licenseType: 'Лицензия на рабочее место / сервер (бессрочная или годовая)',
    match: /криптопро|cryptopro/i,
    quantity: { answerKey: 'workstations_count', unit: 'лиц.', fallback: 'По числу рабочих мест' },
    sourceUrl: 'https://www.cryptopro.ru/products/csp',
  },
];

export const VENDOR_HARDWARE: VendorHardwareProduct[] = [
  {
    id: 'yadro-vegman',
    kind: 'hardware',
    category: 'server',
    name: 'Серверная платформа корпоративного класса YADRO VEGMAN',
    model: 'YADRO VEGMAN R220 G2 (Rack 2U)',
    vendor: 'ООО «КНС ГРУПП» (YADRO)',
    reestrMinpromtorg:
      'Единый реестр российской радиоэлектронной продукции Минпромторга РФ (ПП РФ № 878 / № 719)',
    defaultSpecs:
      '2x Intel Xeon Scalable, до 32x DDR4-3200 ECC, 2x 960 GB NVMe Boot, Hardware RAID, 4x 10/25GbE SFP28, 2x 1200W Redundant PSU, модуль удалённого управления BMC',
    formFactor: '2U Rackmount',
    match: /yadro|ядро|vegman|вегман/i,
    quantity: { answerKey: 'servers_count', unit: 'шт.', fallback: '2 шт.' },
    sourceUrl: 'https://yadro.com/servers/vegman',
    verifiedAt: '2026-08-26',
  },
  {
    id: 'aquarius-server',
    kind: 'hardware',
    category: 'server',
    name: 'Серверная платформа Aquarius',
    model: 'Aquarius T50 D224CF (Rack 2U)',
    vendor: 'ГК «Аквариус»',
    reestrMinpromtorg:
      'Единый реестр российской радиоэлектронной продукции Минпромторга РФ (ПП РФ № 878 / № 719)',
    defaultSpecs:
      '2x Intel Xeon Scalable, до 24x DDR4 ECC, Hardware RAID, 2x 10GbE, резервируемые блоки питания, BMC',
    formFactor: '2U Rackmount',
    match: /aquarius|аквариус/i,
    quantity: { answerKey: 'servers_count', unit: 'шт.', fallback: '2 шт.' },
    sourceUrl: 'https://www.aq.ru',
  },
  {
    id: 'yadro-tatlin',
    kind: 'hardware',
    category: 'storage',
    name: 'Система хранения данных (СХД All-Flash NVMe)',
    model: 'YADRO TATLIN.UNIFIED / Скала^р СХД',
    vendor: 'ООО «КНС ГРУПП» (YADRO)',
    reestrMinpromtorg:
      'Единый реестр российской радиоэлектронной продукции Минпромторга РФ (ПП РФ № 878)',
    defaultSpecs:
      'Двухконтроллерная архитектура (Active-Active), кэш-память 128 GB, полезная ёмкость от 20 TB NVMe TLC, 8x 16/32Gb FC / 25GbE iSCSI, снапшоты, репликация',
    formFactor: '2U/4U Rackmount',
    match: /tatlin|татлин|схд|storage|скала/i,
    quantity: { answerKey: 'storage_systems_count', unit: 'компл.', fallback: '1 компл.' },
    sourceUrl: 'https://yadro.com/tatlin/unified',
    verifiedAt: '2026-08-26',
  },
  {
    id: 'usergate-appliance',
    kind: 'hardware',
    category: 'appliance',
    name: 'Аппаратная платформа межсетевого экрана UserGate Hardware Appliance',
    model: 'UserGate C150 / D200 / F8000',
    vendor: 'ООО «Юзергейт»',
    reestrMinpromtorg: 'Единый реестр российской радиоэлектронной продукции Минпромторга РФ',
    defaultSpecs:
      'Отказоустойчивая пара HA (Active-Passive), пропускная способность NGFW от 10 Гбит/с, bypass-порты, резервированные блоки питания',
    formFactor: '1U Rackmount',
    match: /usergate|ngfw|юзергейт/i,
    quantity: { answerKey: 'ngfw_clusters_count', multiplier: 2, unit: 'шт.', fallback: '2 шт.' },
    sourceUrl: 'https://www.usergate.com/ru/products/hardware-platforms',
    verifiedAt: '2026-08-26',
  },
  {
    id: 'vipnet-coordinator-hw',
    kind: 'hardware',
    category: 'crypto',
    name: 'Криптошлюз ViPNet Coordinator HW 4 (аппаратная платформа)',
    model: 'ViPNet Coordinator HW 1000 / HW 5000',
    vendor: 'АО «ИнфоТеКС»',
    reestrMinpromtorg: 'Единый реестр российской радиоэлектронной продукции Минпромторга РФ',
    defaultSpecs:
      'Аппаратный шлюз ГОСТ-VPN, класс защиты КС3, шифрование каналов по ГОСТ 28147-89 / ГОСТ Р 34.12-2015, кластеризация Active-Passive',
    formFactor: '1U Rackmount',
    match: /vipnet|випнет|гост-?vpn/i,
    quantity: { answerKey: 'vpn_tunnels_count', unit: 'шт.', fallback: '2 шт.' },
    sourceUrl: 'https://infotecs.ru/products/vipnet-coordinator-hw/',
    verifiedAt: '2026-08-26',
  },
];
