import { IndustryPreset } from '../types';

/** Полный пресейл-опросник IDM / IGA с JML, RBAC/SoD и рекертификацией. */
export const IDM_ACCESS_MANAGEMENT_PRESET: IndustryPreset = {
  id: 'preset-idm-access-management',
  name: 'Внедрение IDM / IGA и управление жизненным циклом доступа',
  category: 'security',
  description:
    'Полный пресейл-профиль IDM/IGA: идентичности и мастер-источники, целевые системы, JML-нагрузка, роли и назначения, заявки, SoD, рекертификация, PAM, HA, SLA провижининга и требования к аудиту.',
  workDayHours: 6,
  includeWeekends: false,
  defaultMarginPercent: 28,
  defaultRoleRates: {
    architect: 5000,
    engineer: 4000,
    analyst: 3800,
    consultant: 4400,
    developer: 4000,
    pm: 4200,
  },
  fields: [
    { label: 'Количество управляемых идентичностей', key: 'identities_count', type: 'number', required: true, order: 0 },
    { label: 'Количество целевых систем для интеграции', key: 'target_systems_count', type: 'number', required: true, order: 1 },
    { label: 'Количество кадровых / мастер-источников идентичностей', key: 'authoritative_sources_count', type: 'number', required: true, order: 2 },
    { label: 'Количество бизнес-ролей', key: 'business_roles_count', type: 'number', required: true, order: 3 },
    { label: 'Среднее количество назначений / полномочий на идентичность', key: 'avg_entitlements_per_identity', type: 'number', required: true, order: 4 },
    { label: 'Среднее количество JML-событий в сутки', key: 'jml_events_per_day', type: 'number', required: true, order: 5 },
    {
      label: 'Коэффициент пикового JML-потока',
      key: 'jml_peak_factor',
      type: 'select',
      options: ['1.5', '2', '3', '4', '5'],
      required: true,
      order: 6,
    },
    { label: 'Количество маршрутов заявок и согласований', key: 'approval_workflows_count', type: 'number', required: true, order: 7 },
    { label: 'Количество сервисных / технических учетных записей', key: 'service_accounts_count', type: 'number', required: false, order: 8 },
    { label: 'Требуется автоматический Joiner/Mover/Leaver', key: 'jml_automation_required', type: 'checkbox', required: false, order: 9 },
    { label: 'Требуется контроль конфликтов полномочий SoD', key: 'sod_required', type: 'checkbox', required: false, order: 10 },
    { label: 'Требуется периодическая рекертификация прав', key: 'recertification_required', type: 'checkbox', required: false, order: 11 },
    {
      label: 'Периодичность рекертификации',
      key: 'recertification_period',
      type: 'select',
      options: ['Ежемесячно', 'Ежеквартально', 'Раз в полгода', 'Ежегодно'],
      required: false,
      order: 12,
    },
    { label: 'Требуется интеграция с PAM', key: 'pam_integration_required', type: 'checkbox', required: false, order: 13 },
    { label: 'Требуется SSO / интеграция с IdP', key: 'sso_integration_required', type: 'checkbox', required: false, order: 14 },
    { label: 'Требуется HA платформы IDM / IGA', key: 'idm_ha_required', type: 'checkbox', required: false, order: 15 },
    { label: 'Целевая доступность IDM, %', key: 'availability_target_percent', type: 'number', required: true, order: 16 },
    { label: 'SLA автоматического провижининга / блокировки, минут', key: 'provisioning_sla_minutes', type: 'number', required: true, order: 17 },
    {
      label: 'Доля целевых систем без штатного API / коннектора, %',
      key: 'custom_connector_percent',
      type: 'number',
      required: false,
      order: 18,
    },
    {
      label: 'Тип основной службы каталога',
      key: 'directory_platform',
      type: 'select',
      options: ['Microsoft Active Directory', 'ALD Pro', 'FreeIPA', 'Несколько каталогов', 'Определить на обследовании'],
      required: true,
      order: 19,
    },
    { label: 'Сложность модели доступа', key: 'complexity', type: 'complexity', required: true, order: 20 },
    { label: 'Дополнительные требования / ограничения IDM / IGA', key: 'comment', type: 'textarea', required: false, order: 21 },
    { label: 'Цели создания системы (через точку с запятой)', key: 'project_goals', type: 'textarea', required: false, order: 22 },
    { label: 'Измеримые критерии достижения целей («показатель = целевое значение»)', key: 'goal_criteria', type: 'textarea', required: false, order: 23 },
  ],
  stageTemplates: [
    {
      name: 'Обследование идентичностей, каталогов и процессов доступа',
      role: 'analyst',
      baseHours: 36,
      hoursPerUnit: 4,
      driverFieldKey: 'authoritative_sources_count',
      requirements:
        'Исполнитель обязан определить авторитетные источники, каталоги, типы идентичностей, JML-процессы, владельцев ресурсов, текущие заявки/согласования и подготовить реестр интеграций и качества исходных данных.',
      order: 0,
    },
    {
      name: 'Проектирование архитектуры IDM / IGA и модели ролей',
      role: 'architect',
      baseHours: 44,
      hoursPerUnit: 2.5,
      driverFieldKey: 'business_roles_count',
      requirements:
        'Исполнитель обязан разработать архитектуру IDM/IGA, модель ролей и назначений, SoD, владельцев ресурсов, административную модель, SLA JML, HA и требования к журналированию.',
      order: 1,
    },
    {
      name: 'Развертывание платформы IDM / IGA и базовая конфигурация',
      role: 'engineer',
      baseHours: 44,
      hoursPerUnit: 0,
      driverFieldKey: null,
      requirements:
        'Исполнитель обязан развернуть платформу, БД и фоновые сервисы, настроить HA, резервное копирование, мониторинг, административные роли и защищенное взаимодействие компонентов.',
      order: 2,
    },
    {
      name: 'Интеграция мастер-систем и целевых информационных систем',
      role: 'developer',
      baseHours: 28,
      hoursPerUnit: 14,
      driverFieldKey: 'target_systems_count',
      requirements:
        'Исполнитель обязан реализовать коннекторы и преобразование атрибутов, чтение/сверку, провижининг, блокировку/удаление, обработку ошибок, повторные попытки и эксплуатационную диагностику интеграций.',
      order: 3,
    },
    {
      name: 'Настройка JML, заявок и ролевой модели',
      role: 'consultant',
      baseHours: 36,
      hoursPerUnit: 2,
      driverFieldKey: 'approval_workflows_count',
      requirements:
        'Исполнитель обязан настроить Joiner/Mover/Leaver, каталоги доступа, маршруты заявок, делегирование, бизнес-роли, правила автоприсвоения и при применимости контроль SoD.',
      order: 4,
    },
    {
      name: 'Настройка рекертификации и отчетности',
      role: 'consultant',
      baseHours: 24,
      hoursPerUnit: 1.5,
      driverFieldKey: 'business_roles_count',
      requirements:
        'Исполнитель обязан настроить кампании рекертификации, владельцев решений, эскалации, отзыв неподтвержденных прав и отчетность по JML, заявкам, ролям, SoD и аудиту.',
      order: 5,
    },
    {
      name: 'Миграция идентичностей и сверка текущих прав',
      role: 'analyst',
      baseHours: 24,
      hoursPerUnit: 0.025,
      driverFieldKey: 'identities_count',
      requirements:
        'Исполнитель обязан выполнить контролируемую загрузку идентичностей и назначений, дедупликацию, сверку с целевыми системами, разбор orphan-учетных записей и фиксацию исключений.',
      order: 6,
    },
    {
      name: 'Миграция, опытная эксплуатация, обучение и ПМИ',
      role: 'analyst',
      baseHours: 32,
      hoursPerUnit: 0.02,
      driverFieldKey: 'identities_count',
      requirements:
        'Исполнитель обязан провести опытную эксплуатацию JML/заявок/рекертификации, нагрузочную проверку, failover при HA, обучение администраторов и владельцев ресурсов и приемочные испытания по ПМИ.',
      order: 7,
    },
  ],
  riskTemplates: [
    {
      description: 'Авторитетные кадровые данные не содержат стабильных идентификаторов или имеют дубли/пропуски, требующие очистки до автоматизации JML.',
      hours: 28,
      order: 0,
    },
    {
      description: 'Часть целевых систем не имеет поддерживаемого API/коннектора и потребует разработки специализированной интеграции либо полуавтоматического процесса.',
      hours: 28,
      order: 1,
    },
    {
      description: 'Владельцы ресурсов и ролей не определены, а матрица полномочий не согласована до начала настройки RBAC/SoD.',
      hours: 24,
      order: 2,
    },
    {
      description: 'Первичная сверка выявит orphan-учетные записи, избыточные назначения и конфликтующие права, что потребует отдельной волны remediation.',
      hours: 24,
      order: 3,
    },
    {
      description: 'SLA провижининга недостижим для систем с пакетным обменом или ручным исполнением без изменения интеграционного процесса.',
      hours: 16,
      order: 4,
    },
  ],
};
